### PR TITLE
implement snappy add-assertion

### PR DESCRIPTION
**Pull request by pedronis**
ultimately this would be available in some form under snap/snapd, unclear if we want this on master or just the demo branch, otoh it shouldn't interfere with anything atm

needs #217

### CODE REVIEW

**Comment by niemeyer** [comment]
The implementation looks very nice. Great flow to read.

Missing tests?

**Comment by pedronis** [comment]
@niemeyer so I talked with @chipaca and @mvo5, seems the typical approach is to have an integration test for things under cmd/.

Issue is that the test would have to install a dummy trusted key from inside the test, that's doable of course. 

But that makes me of two minds about landing this in master, it's not in the right place yet (snappy vs snap/snapd) and we don't have yet an official trusted key so it won't work out of the box but needs manual installing of a dummy one to play, on the positive side the error one gets is very clear about that being the issue.

**Comment by mvo5** [comment]
Looks nice, +1. Stuff under cmd is often just calling into high level helpers wich then are unit tested. For some bits we have tests in cmd. One way might be to have a "assert.AddFromFile()" that is called from doAddAssertion() and can easily be unit tested from the assert_test package. But an integration test would work too.

**Comment by pedronis** [comment]
@niemeyer @mvo5 if we think it's reasonable to have this on master I would go with an integration test or no tests for the time being.  I'm not sure the helper AddFromFile would be needed later if the operation is split in client/server halves.

**Comment by pedronis** [comment]
I start to think it's probably premature to merge this to master, I'll make a PR to land it to the demo branch only for now, either way is not much code

**Comment by pedronis** [comment]
making a new PR to get this just into the demo branch for now

**Pull request closed without merging**
