### PR TITLE
interfaces: add network-observe from ubuntu-core-security

### PR DESCRIPTION
**Pull request by jdstrand**

### CODE REVIEW

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by chipaca** [comment]
ok to test

**Comment by mvo5** [comment]
Fine, same comments about tests as for log-observer.

**Comment by zyga** [comment]
LGTM (reviewed with per-patch diff)

FYI: for tests I'd keep them as is. It will be easier to add interface-specific tests (e.g. regression checks or anything similar) this way. We could spend some time de-duplicating them after 16.04.

**Comment by niemeyer** [comment]
I'm merging all security interface branches, and adding a single card in Trello to track the points raised which were not addressed.

**Pull request merged**
