### PR TITLE
client: filter snaps with a seach query

### PR DESCRIPTION
**Pull request by stevenwilkin**
Corresponds with #371 but could potentially be landed beforehand.

### CODE REVIEW

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by mvo5** [comment]
:+1:

**Comment by chipaca** [comment]
I'm going to be an arse and say let's not land this until #384 lands. It'll then need deconflicting, but it'll be testing the right things.

**Comment by stevenwilkin** [comment]
Makes sense @chipaca, I'll rework this when the times comes.

**Comment by niemeyer** [comment]
Leaving for @chipaca

**Comment by stevenwilkin** [comment]
Updated with the @chipaca goodness.

**Comment by chipaca** [comment]
:+1:

**Comment by chipaca** [comment]
retest this please

**Pull request merged**
