### PR TITLE
Added method SetUbuntuArchitecture to override detected arch.

### PR DESCRIPTION
**Pull request by fancycode**
This can be used by ubuntu-device-flash when cross-building OEM snaps to
change the architecture to the one from the hardware in the OEM snap.

### CODE REVIEW

**Comment by elopio** [comment]
Hello!
Thanks for your contribution. One of the devs will review it soon. In the meantime, could you please take a look at the contributors agreement? http://www.ubuntu.com/legal/contributors/
In order to contribute code with snappy, we'll need you to sign it. If you have any questions, please let us know.

**Comment by sergiusens** [comment]
Why do we need this? We already have
https://github.com/ubuntu-core/snappy/blob/master/snappy/arch.go#L45

**Comment by fancycode** [comment]
@elopio: I'm in the "strukturag" group on launchpad where we have signed the CLA (I'm also registered as "fancycode").

@sergiusens: See my comment in the proposed branch on Launchpad:
https://code.launchpad.net/~fancycode/goget-ubuntu-touch/set-oem-architecture/+merge/276260/comments/698427
The architecture checks when installing additional snaps in the image are using the API from the "helpers" package, that's why I introduced a "Set..." API there too and are calling both from here.

Feel free to ping me on #snappy for further questions/suggestions.

**Comment by fancycode** [comment]
Updated based on feedback from the corresponding change on LP.

**Comment by niemeyer** [comment]
This is not quite right, in the sense that goarch is a variable that stores the architecture as understood by Go, rather than one that is known to Ubuntu. That said, the patch is well-meaning, and highlights a minor problem in the API that we ought to fix: there shouldn't be two sets of functions doing the same thing in slightly different ways in separate packages.

I suggest removing all related functionality from the helpers package, moving the necessary pieces into snappy/arch.go, and dropping the UbuntuArchitecture function in favor of computing it on an init() function that stores the result straight into the local arch variable. I also suggest taking this chance to shorten the remaining functions and type name to Arch rather than Architecture.

@fancycode I'm closing this PR for bookkeeping, but please reopen it when it reflects these changes.

**Comment by fancycode** [comment]
Thanks for your feedback, my goal was to keep the modifications minimal to support my use case. I'll check when I get some time to look into your proposed changes.

**Pull request closed without merging**
