### PR TITLE
daemon, overlord, snappy, docs: drop separation between removed and purged

### PR DESCRIPTION
**Pull request by chipaca**
Hopefully I didn't miss anything!

### CODE REVIEW

**Comment by niemeyer** [comment]
LGTM!

**Comment by elopio** [comment]
Please update the integration tests:
purgeSuite.TestPurgeHonoursInstalledFlagForNotRemovedPackage
purgeSuite.TestPurgeRemovesDataForDeactivatedNotRemovedPackage

**Comment by chipaca** [comment]
@elopio whoops! Will do. Tomorrow.

**Comment by mvo5** [comment]
Looks fine! We could add a test somewhere that the data is really removed (by making a fake package, adding some data etc). But we can also add this later, maybe via integration tests.

**Pull request merged**
