### PR TITLE
integration-tests: add snap_example_test.go

### PR DESCRIPTION
**Pull request by mvo5**
Start having more integration tests for the `snap` command by copying the existing tests from example_test.go (the ones that make sense).

Please do not merge until the integration tests actually pass.

### CODE REVIEW

**Comment by niemeyer** [comment]
I wonder if --allow-unauthenticated is actually --devel as well.

LGTM either way.

**Comment by mvo5** [comment]
retest this please

**Comment by pedronis** [comment]
retest this please

**Comment by mvo5** [comment]
This is passing now, there is one real bug uncovered by this in the progress-adapter code.

**Comment by pedronis** [comment]
@mvo5 looks like a good start

**Pull request merged**
