### PR TITLE
overlord: split out the managers and State to their own subpackages of overlord

### PR DESCRIPTION
**Pull request by pedronis**

### CODE REVIEW

**Comment by pedronis** [comment]
requires #526 

haven't moved StateEngine itself, could go under state/ not sure is that useful to do that

**Comment by niemeyer** [comment]
Nice, like that a lot. It'll probably make sense to move stuff such as SnapManager.Install(name) into snapstate.Install(state, name), so anyone can call it as long as they hold a state at hand (no need to have the actual manager instance at hand).

Feels fine to have the StateEngine at overlord still.

**Comment by niemeyer** [comment]
Ah, and LGTM

**Comment by pedronis** [comment]
yes this looks like a good direction, slightly worried that global helpers while nice will force us because of circular imports to actually have to introduce *state/mgr subpackages as well, oh well, we'll see

**Comment by niemeyer** [comment]
I hope we don't need to do that. The better alternative is to organize the code so the imports are indeed one way. For that, we may need to have logic along the lines of snapstate.AssertsVetoed, so that it's the assertstate package that is calling it out from outside, but again that sounds like a good thing. It means we have some clear lines between who knows about whom.

**Comment by chipaca** [comment]
:+1:

**Comment by chipaca** [comment]
retest this please

**Pull request merged**
