### PR TITLE
scripts: move the script to get dependencies to a separate file

### PR DESCRIPTION
**Pull request by elopio**
This will help us writing cleaner scripts for the different integration
tests scenarios.

### CODE REVIEW

**Comment by fgimenez** [comment]
:+1:

**Comment by stevenwilkin** [comment]
Perhaps worthwhile mentioning this script in [the dependencies section of the README](https://github.com/ubuntu-core/snappy#dependencies-handling), otherwise :+1:

**Comment by elopio** [comment]
@stevenwilkin I added a small line. Please check if that's what you wanted.

Thanks for the reviews!

**Comment by stevenwilkin** [comment]
Good stuff @elopio !

**Pull request merged**
