### PR TITLE
interfaces: add system-observe from ubuntu-core-security

### PR DESCRIPTION
**Pull request by jdstrand**
interfaces: add system-observe from ubuntu-core-security

### CODE REVIEW

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by chipaca** [comment]
ok to test

**Comment by mvo5** [comment]
Fine, but comments about tests from log-observer apply here too.

**Comment by zyga** [comment]
LGTM

**Comment by niemeyer** [comment]
I'm merging all security interface branches, and adding a single card in Trello to track the points raised which were not addressed.

**Pull request merged**
