### PR TITLE
Close the test server after the websocket connection has been initiated

### PR DESCRIPTION
**Pull request by stevenwilkin**
In response to [this build failure](https://travis-ci.org/ubuntu-core/snappy/jobs/114732721).

### CODE REVIEW

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by mvo5** [comment]
Looks good

**Pull request merged**
