### PR TITLE
many: prepare for opengl support on classic

### PR DESCRIPTION
**Pull request by mvo5**
This branch prepare the snappy side of opengl support on classic. The idea is that the ubuntu-core-launcher bind mounts the hosts libgl directory into /var/lib/snapd/lib/gl and via the ld.so.conf.d mechanism and SNAP_LIBRARY_PATH (that will get picked up by snapcraft) the apps can link to that libgl. The code also adds an opengl interface so that the apps can get the permission to access the device.

### CODE REVIEW

**Comment by niemeyer** [comment]
LGTM

**Comment by mvo5** [comment]
retest this please

**Comment by mvo5** [comment]
retest this please

**Comment by mvo5** [comment]
retest this please

**Comment by zyga** [comment]
Looks good. I'd love an entry in docs/interfaces.md (even inline in github editor)

**Comment by zyga** [comment]
Should we auto-add opengl plug to the OS snap? (implicit slot)

**Pull request merged**
