### PR TITLE
osutil: make go vet happy again

### PR DESCRIPTION
**Pull request by chipaca**
Go vet is silly. Work around it.

### CODE REVIEW

**Comment by zyga** [comment]
I'd love to have a richer commit message that actually explains something.

**Comment by niemeyer** [comment]
Awkward, but +1.

**Comment by mvo5** [comment]
I wonder if we should report this upstream as a bug (or is it none?). Maybe a comment on the code? but not really important.

**Comment by chipaca** [comment]
@mvo5 I've poked @mwhudson with http://pastebin.ubuntu.com/14858123/ to see if this is upstream or ours (ubuntu's), but I suspect the former. We'll get it filed in the right place eventually.

**Comment by chipaca** [comment]
https://bugs.launchpad.net/ubuntu/+source/golang/+bug/1541014 FWIW

**Comment by mwhudson** [comment]
Also https://github.com/golang/go/issues/14201

**Comment by mwhudson** [comment]
I think Ian's fix (https://go-review.googlesource.com/19174) suggests that maybe you boiled the example down a little too much?

**Comment by chipaca** [comment]
Perhaps! Can you try it with the actual code above? Otherwise I'll do it in
my morning

**Comment by mwhudson** [comment]
Ah no apparently it's OK and still fixes the crash.

**Comment by mwhudson** [comment]
(when i revert 9a0fc4f64a91ca035a1388942fa519e67aa78c5f)

**Pull request merged**
