### PR TITLE
cmd/snap: replace skip-help with empty description

### PR DESCRIPTION
**Pull request by zyga**
Signed-off-by: Zygmunt Krynicki <zygmunt.krynicki@canonical.com>

### CODE REVIEW

**Comment by mvo5** [comment]
This looks fine in itself, a bit more context would be nice. I.e. why is the skip-help replaced with the empty description? I assume it is because  we want the help output in a certain way(?) but being explicit about the goal would be nice. Otherwise +1.

**Comment by zyga** [comment]
Hey

It is becaus of upstream pat evolution. What use use use done b skip-help is no don by havi no description.

**Comment by mvo5** [comment]
I have a bit of trouble parsing this sentence, but I think it means that the upstream go-flags patch skips the help if there is no description. If this is the case: :+1:

**Comment by zyga** [comment]
Sorry, the earlier message was written on a phone. Yes, you are correct. When there is no description then certain (new) behavior of go-flags is triggered. Earlier, with the first evolution of my patch for go-flags, that same behavior was triggered when the "skip-help" option was used.

**Pull request merged**
