### PR TITLE
store: only use remoteSnap.pkg.DownloadURL if there is actually such URL

### PR DESCRIPTION
**Pull request by mvo5**
This fixes failing tests on my system that happens to have a sso token.

### CODE REVIEW

**Comment by pedronis** [comment]
I suspect the better fix would be to override ReadStoreToken in tests but we'll need to redo this stuff soon

**Comment by mvo5** [comment]
@pedronis Well, I think trying to use the  (non-anonymous) URL even if it is empty is a bug in itself.

**Comment by niemeyer** [comment]
Can we have a unit test that fails in general if that's broken?

**Comment by mvo5** [comment]
Thanks for the feedback. Contemplating about this over the weekend I think my fix is not good. Given that this is a tests only issue, I think now it should also only be fixed in the tests. I will create a new PR.

**Pull request closed without merging**
