### PR TITLE
daemon: move UUID into its own package

### PR DESCRIPTION
**Pull request by stevenwilkin**
I need to do some UUID generation but the current package layout causes a circular dependency so move this into it's own package.

### CODE REVIEW

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by niemeyer** [comment]
LGTM.

On a note unrelated to the move, why are we using UUIDs here? What's the benefit compared to a shorter random id?

**Comment by stevenwilkin** [comment]
Cheers @niemeyer. I needed some way of differentiating between subscribers and the UUID code was already there. If you think that using something like a string of random ints would be better then that's fine with me and I can close #527.

**Comment by stevenwilkin** [comment]
Hmm, my comment was related to #530...

**Comment by zyga** [comment]
+1

**Comment by niemeyer** [comment]
I suggest instead having a random id generator that is fed a len and outputs a random string (likely base32 without vowels to avoid offensive terms embedded in them).

I'm closing this one and #530 waiting for those changes. Please reopen when ready to go.

**Comment by stevenwilkin** [comment]
I'll look into this on Monday

**Pull request closed without merging**
