### PR TITLE
many: fix sideloading snaps and (re)add tests for this

### PR DESCRIPTION
**Pull request by mvo5**
Sideloading snaps crashes currently because it uses the old crappy^Wsnappy pkg code. This branch makes it use the stateengine instead. Plus it re-enables some of the integration tests that would have catched this regression.

### CODE REVIEW

**Comment by chipaca** [comment]
This needs deconflicting, and the integration tests will need a tweak due to the new format of `snap list`. But :+1:

**Comment by zyga** [comment]
Hmm, looks good. +1

**Comment by pedronis** [comment]
@mvo5 do we need to check flags (that not auth is alowed?) somewhere here?

**Comment by mvo5** [comment]
@pedronis thanks! I added a FIXME for this

**Pull request merged**
