### PR TITLE
snappy: remove cmd/snappy (superseded in favour of cmd/snap)

### PR DESCRIPTION
**Pull request by mvo5**

### CODE REVIEW

**Comment by zyga** [comment]
Woot, LGTM

**Comment by niemeyer** [comment]
retest this please

**Comment by niemeyer** [comment]
Missing update-pot it seems.

**Comment by fgimenez** [comment]
There are some leftover bits in the integration tests too, already submitted a PR for that mvo5/snappy#9

**Comment by mvo5** [comment]
retest this please

**Comment by niemeyer** [comment]
retest this please

**Pull request merged**
