### PR TITLE
make hooks run with a default locale

### PR DESCRIPTION
**Pull request by chipaca**

### CODE REVIEW

**Comment by zyga** [comment]
There's also some weird influence of LANGUAGE and LANG but this is a much welcome change, +1

**Comment by chipaca** [comment]
For perl, setting `LC_ALL` has priority overy everything else, IIRC. A quick read of [perllocale](http://perldoc.perl.org/perllocale.html) seems to confirm this hasn't changed since I was a perl hacker two lives ago.

**Comment by mvo5** [comment]
I wonder if it would make more sense to set this in /etc/profile.d/ for now and revert it at this one place once we start support locales configuration. I'm a bit worried that at some point a hook may want to return localized messages. But I'm probably overthinking this given that in the webdm i18n world we will have to set the locale environment for the hook anyway based on the language http header we got from webdm. So I think its fine because we will have to touch this for fully i18n again anyway :)

**Comment by chipaca** [comment]
When we have i18n we'll need to change this, independently of how webdm tells us about l10n. I don't care whether it's in code or configuration really; if you think something in profile.d would be better, I can do that instead. let me know :-)

**Comment by mvo5** [comment]
Lets do it here for now - we need to touch this anyway again when we add i18n so no waste :) thanks a lot for this branch!

**Pull request merged**
