### PR TITLE
cmd/snap, debian: move manpage generation to depend on an environ key; also, fix completion

### PR DESCRIPTION
**Pull request by chipaca**

### CODE REVIEW

**Comment by mvo5** [comment]
Unit tests are failing.

**Comment by chipaca** [comment]
EVERYTHING IS TERRIBLE!

**Comment by niemeyer** [comment]
I suggest putting that under "snap help --man".

**Comment by mvo5** [comment]
:+1: once the tests are good. Fwiw, I personally would prefer a hidden internal command over an environment.

**Comment by niemeyer** [comment]
It doesn't even have to be hidden.. `snap help --man` looks pretty neat.

**Comment by mvo5** [comment]
:+1:

**Pull request merged**
