### PR TITLE
Rename /apps -> /snaps (same for data, and user-data)

### PR DESCRIPTION
**Pull request by mvo5**
Also remove /gadget which has some unfortuante side-effects
in the lightweight code. We need a better concept here as
lightweight does not deals with os/kernel types at all
currently.

Oh, forgot to mention this - this will break every installed apps.

### CODE REVIEW

**Comment by niemeyer** [comment]
LGTM!

**Comment by mvo5** [comment]
retest this please

**Comment by mvo5** [comment]
retest this please

**Comment by mvo5** [comment]
retest this please

**Comment by mvo5** [comment]
retest this please

**Comment by mvo5** [comment]
retest this please

**Pull request merged**
