### PR TITLE
Support HOME for systemd units

### PR DESCRIPTION
**Pull request by sergiusens**
%h does not work with systemd as it is PID1. From the manpage:

> Please note that specifiers "%U", "%h", "%s" are mostly useless when
> systemd is running in system mode.

LP: #1466234

### CODE REVIEW

**Comment by chipaca** [comment]
:+1:

**Comment by zyga** [comment]
+1

**Comment by zyga** [comment]
@sergiusens can you please have a look at the broken unit tests. It seems to require some attention.

**Comment by sergiusens** [comment]
@zyga yeah, on it

**Comment by sergiusens** [comment]
As in, running locally now ;-)

**Comment by sergiusens** [comment]
```
         ▌     ▐            ▜   ▌             ▗ ▌  ▜
     ▌  ▌▛▀▖▝▀▖▜▀  ▞▀▖▞▀▖▌ ▌▐ ▞▀▌ ▛▀▖▞▀▖▞▀▘▞▀▘▄ ▛▀▖▐ ▌ ▌ ▞▀▌▞▀▖ ▌  ▌▙▀▖▞▀▖▛▀▖▞▀▌
     ▐▐▐ ▌ ▌▞▀▌▐ ▖ ▌ ▖▌ ▌▌ ▌▐ ▌ ▌ ▙▄▘▌ ▌▝▀▖▝▀▖▐ ▌ ▌▐ ▚▄▌ ▚▄▌▌ ▌ ▐▐▐ ▌  ▌ ▌▌ ▌▚▄▌
      ▘▘ ▘ ▘▝▀▘ ▀  ▝▀ ▝▀ ▝▀▘ ▘▝▀▘ ▌  ▝▀ ▀▀ ▀▀ ▀▘▀▀  ▘▗▄▘ ▗▄▘▝▀   ▘▘ ▘  ▝▀ ▘ ▘▗▄▘
```

**Comment by kyrofa** [comment]
Isn't this actually LP: #1541898 though?

**Comment by sergiusens** [comment]
@kyrofa there were many many bugs opened, this one matched somewhat

**Pull request merged**
