### PR TITLE
integration-tests: run the installed snappy when there is no config file

### PR DESCRIPTION
**Pull request by elopio**

### CODE REVIEW

**Comment by zyga** [comment]
+1

**Comment by elopio** [comment]
retest this please

**Comment by elopio** [comment]
retest this please

**Comment by elopio** [comment]
retest this please

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by elopio** [comment]
merge this please

**Comment by elopio** [comment]
(I'm just taking advantage of the current errors to test a little something here)

**Pull request merged**
