### PR TITLE
integration-tests: reenable failure tests

### PR DESCRIPTION
**Pull request by mvo5**
[Based on https://github.com/ubuntu-core/snappy/pull/873]

### CODE REVIEW

**Comment by niemeyer** [comment]
There's something strange with this branch. It says no conflicts, but the diff shows code that was definitely changed significantly on master, and the diff also seems to include content from its base.

**Comment by mvo5** [comment]
I remerged with master

**Comment by mvo5** [comment]
retest this please

**Comment by niemeyer** [comment]
Thanks!

**Pull request merged**
