### PR TITLE
snap,snappy: add and use snap.AppInfo.CommandLine

### PR DESCRIPTION
**Pull request by zyga**
This branch removes a TODO from `snappy/` by adding a new helper method on snap.AppInfo.
The new CommandLine method returns the full path of the command that a given app would run.
In the end that command line is used in generated executable wrappers.

### CODE REVIEW

**Comment by pedronis** [comment]
this makes some of the stripGlobalRootDir in snappy/ pointless, which I think they are because we don't do wrapper generation in u-d-f anymore, but that's why I was reluctant to proceed doing this

**Comment by pedronis** [comment]
also the tests look worse :/

**Comment by niemeyer** [comment]
... and Command _already is_ a Command Line. Please address these concerns with @pedronis.

**Comment by pedronis** [comment]
my main concern in this area is that what we want really need in the end is full launcher invocation and also that binaries.go and systemd have some repetition/wrong layering (also snapenv) related to this and other things, I would leave this alone until we move those bits out of snappy into wrappers/ and then refactor these things more holistically

**Comment by zyga** [comment]
This was just a low hanging fruit, I'm fine with not merging this and attempt a bigger/better re-factoring that moves binaries/services out of snappy and makes the code nicer overall. The biggest benefit out of this endeavour was the already merged Revision-0 fix.

**Pull request closed without merging**
