### PR TITLE
daemon: refactor makeErrorResponder()

### PR DESCRIPTION
**Pull request by zyga**
The control flow around makeErrorResponder() was complex so I've cleaned
it up a little. I've removed the part that logged requests as it was the
wrong place to do so and seemed to be of little value.

Signed-off-by: Zygmunt Krynicki <zygmunt.krynicki@canonical.com>

### CODE REVIEW

**Comment by niemeyer** [comment]
Much better, thanks! :+1:

**Comment by mvo5** [comment]
Looks good! Maybe worth merging trunk to ensure the integration tests work?

**Comment by chipaca** [comment]
Hmm. Can we get back the logging of the whole error before sending it out?

**Comment by zyga** [comment]
@chipaca per what @niemeyer said in #405 we should not log unauthenticated requests.

**Pull request merged**
