### PR TITLE
Added myappsURL function to get MyApps API base URL.

### PR DESCRIPTION
**Pull request by matiasb**
Added helper to get MyApps base URL for API requests. Based on existing helpers for CPI and SSO.

### CODE REVIEW

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by niemeyer** [comment]
Thanks!

**Comment by niemeyer** [comment]
Sorry, forgot to fix the summary before merging.

**Pull request merged**
