### PR TITLE
integration tests: make the update OS test pass

### PR DESCRIPTION
**Pull request by elopio**

### CODE REVIEW

**Comment by elopio** [comment]
retest this please

**Comment by elopio** [comment]
retest this please

**Comment by mvo5** [comment]
Nice!

**Comment by elopio** [comment]
this makes it pass locally, but it still failed in the cloud. I need to keep debugging.

**Comment by chipaca** [comment]
:+1:
I'd say land this (thank you!) and additional work in an additional branch.

**Pull request merged**
