### PR TITLE
autopkgtest: added an initial test

### PR DESCRIPTION
**Pull request by elopio**

### CODE REVIEW

**Comment by elopio** [comment]
This test comes with a test, of course, how could it be different? :smile: 
ubuntu-core/snappy-jenkins/pull/96
it will run in every pull request. However, it's currently blocked by https://bugs.launchpad.net/snappy/+bug/1555140 ( /me looks @chipaca )

**Comment by fgimenez** [comment]
:+1: once travis is happy

**Comment by mvo5** [comment]
looks great!

**Comment by zyga** [comment]
+1

**Comment by elopio** [comment]
merge this please

**Pull request merged**
