### PR TITLE
Remove the NewAutopkgtest function.

### PR DESCRIPTION
**Pull request by elopio**
As suggested by @niemeyer in a code review, I'm getting rid of the useless func.

### CODE REVIEW

**Comment by zyga** [comment]
+1

**Comment by sergiusens** [comment]
Should it not be `AutoPkgTest`?
Also, the package namespace and the struct have the same name, is there any better naming that can be done here?

Feel free to ignore me completely :wink:

**Comment by niemeyer** [comment]
LGTM, thanks!

**Comment by elopio** [comment]
@sergiusens yes, I will follow up with a rename to AutoPkgTest.
If you have a better name, please let me know. Maybe only Test ?

**Pull request merged**
