### PR TITLE
interface: add home security policy

### PR DESCRIPTION
**Pull request by jdstrand**
Note, I intentionally left out seccomp rules for this since there are none for 'home'. I wasn't sure how to add a test that said that seccomp should not be there....

### CODE REVIEW

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by zyga** [comment]
whitelist this please

**Comment by zyga** [comment]
This looks good but we should also add it to "known interfaces", see ``all.go`` in the same directory (and all_test.go please).

**Pull request merged**
