### PR TITLE
integration-tests: rename to acceptance-tests

### PR DESCRIPTION
**Pull request by elopio**
LP: #1579932

### CODE REVIEW

**Comment by elopio** [comment]
restest this please

**Comment by elopio** [comment]
@plars hey, this will likely affect you. I'm sorry.

**Comment by fgimenez** [comment]
:+1:

**Comment by niemeyer** [comment]
I don't quite see why we would change that?

**Comment by niemeyer** [comment]
Acceptance is why you might run the tests..

**Comment by niemeyer** [comment]
Sorry, closed by mistake.. would like to hear the reasoning.

**Comment by elopio** [comment]
We discussed today about making the layers of our tests clearer. Integration doesn't say what pieces we are integrating, so we are calling the same way some test that integrate two pieces of lower level layers.
We decided that we are going to use this layer to accept or not a new release. And that the style of the tests will be exercising the system through the CLI. This is the first of the cleanups on that  direction.

**Comment by elopio** [comment]
retest this please

**Comment by niemeyer** [comment]
Okay, I'm going to close this bikeshed so we can move forward. Every test we have is used as an acceptance blocker: unit tests, static tests, integration tests. It feels wrong to have one of these specially labeled as being the acceptance tests.

If that doesn't feel right, we'll need some more rationale about why that's an invalid point.

**Comment by elopio** [comment]
wait, didn't you say that we would talk about it today? You just close it instead, not nice.

**Comment by niemeyer** [comment]
Happy to talk still. Closing means it must not be merged until further notice, for the reasons politely stated.

We're in the same room. Feel free to actually talk too. :)

**Pull request closed without merging**
