### PR TITLE
integration-tests: teach some new trick to the fake store, reenable the app refresh test

### PR DESCRIPTION
**Pull request by pedronis**
Teaches the fake store about exact match /search usages as utilised by installation/refresh atm.

Added a snapbuild executable that is built only for integration tests, refresh ones seem to require building snaps under sudo so having an external executable was the simplest solution to that.

### CODE REVIEW

**Comment by pedronis** [comment]
I wanted also to switch the tests and the fake store to have sideinfo/store-like information on the side to serve but need chipaca's branch exposing snap ids first for that to be doable/meaningful.

**Comment by mvo5** [comment]
:+1:

**Comment by zyga** [comment]
Looks good +1

**Comment by fgimenez** [comment]
Nice! :+1:

**Pull request merged**
