### PR TITLE
integration-tests: add the first classic dimention tests

### PR DESCRIPTION
**Pull request by elopio**

### CODE REVIEW

**Comment by elopio** [comment]
@mvo5 I think I've found a bug here. The classic file is kept in /tmp/ after it was destroyed. So after enabling and destroying classic a few times I ran out of space in /tmp. I think we should delete the file.

Also, I don't know how to interact with the shell. The next test I want to write is to install something with apt-get, but if I exec a command after entering the classic shell, it is still received by the snappy shell.

**Comment by elopio** [comment]
oh, we need a new firewall exception: Error: failed to downlaod lxdIndexUrl: Get https://images.linuxcontainers.org/meta/1.0/index-system: dial tcp 192.99.34.219:443: i/o timeout
I'm in bed already. @fgimenez could you please make the request?

**Comment by mvo5** [comment]
Code looks nice and straightforward, :+1:

**Comment by elopio** [comment]
retest this please

**Comment by elopio** [comment]
retest this please

**Comment by elopio** [comment]
retest this please

**Comment by elopio** [comment]
Can you help me with this one @fgimenez ?
I can wget https://images.linuxcontainers.org/meta/1.0/index-system from a normal ubuntu system in scalingstack if I use the proxy. The proxy env var seems to be properly set, but enable-classic still times out. Any idea what else to check?

**Comment by fgimenez** [comment]
It seems that the `https_proxy` env var was not set for root, and the sudo command required for enabling classic mode was unable to see it. Take a look at [1], which uses the branch at [2] based on yours, just adds `env https_proxy=<the_proxy>` after sudo to the `enable-classic` command.

[1] http://162.213.35.179:8080/job/classic-test/15/console
[2] https://github.com/ubuntu-core/snappy/compare/master...fgimenez:test/classic_mode?expand=1

**Comment by mvo5** [comment]
@elopio thanks for finding the bug that there is a leftover file in /tmp. I pushed a fix for this now.

**Comment by niemeyer** [comment]
LGTM

**Pull request merged**
