### PR TITLE
integration-tests: update 15.04 branch from master to accept http-proxy flag

### PR DESCRIPTION
**Pull request by fgimenez**

### CODE REVIEW

**Comment by fgimenez** [comment]
retest this please

**Comment by fgimenez** [comment]
retest this please

**Comment by mvo5** [comment]
Thanks for this branch. I'm a little confused that we need kernel/os snap changes in the 15.04 branch. Could you elaborate a bit why this is the case? I was assuming for 15.04 we still build the 15.04 base image using the 15.04 machinery? Or am I missing something because of jet-lag?

**Comment by fgimenez** [comment]
@mvo5 thx for the review! :) no kernel or os snap changes are needed for this branch, I've just copied here the relevant files (integration-tests/main.go and the integration-tests/testutils/{autopkgtest,build,image} packages) fom the master branch so that we can use here the http-proxy flag. 

In those files there have been changes related to the default parameters for udf (--os, --kernel and --gadget) that wouldn't be needed in this branch, we could probably extract just the changes needed for including the top-level http-proxy flag, it was just quicker to just copy the files, if you think it should be better to extract the changes and maintain the modified files pls let me know and i'll push the modifications.

retest this please

**Comment by mvo5** [comment]
@fgimenez Thanks, its fine to copy it, just wanted to double check

**Comment by mvo5** [comment]
retest this please

**Comment by fgimenez** [comment]
We haven't backported the integration test coverage metrics support to the 15.04 branch and the report was returning errors in the test execution, already fixed
retest this please

**Pull request merged**
