### PR TITLE
Rename Device to DeviceSerial.

### PR DESCRIPTION
**Pull request by emgee**
Renamed as much as seems sensible. I left some doc comments alone as they made more sense (to me) still referring to "device".

### CODE REVIEW

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by chipaca** [comment]
add to whitelist

**Comment by niemeyer** [comment]
That feels like a slightly too-vague term for the assertion type. I'm also missing some context about why this is changing.

**Comment by emgee** [comment]
Decided to call it `device-serial`. I'll update the PR.

**Comment by mvo5** [comment]
retest this please

**Comment by niemeyer** [comment]
LGTM

**Comment by mvo5** [comment]
:+1:

**Pull request merged**
