### PR TITLE
interfaces/dbus: drop superfluous backslash from template

### PR DESCRIPTION
**Pull request by morphis**
Without this dbus-daemon will always fail to parse generated dbus
policies from snapd.

Signed-off-by: Simon Fels <simon.fels@canonical.com>

### CODE REVIEW

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by niemeyer** [comment]
Thank you!

**Comment by niemeyer** [comment]
add to whitelist

**Comment by zyga** [comment]
Ohh, nice catch!

**Comment by morphis** [comment]
You guys are fast these days :-)

**Pull request merged**
