### PR TITLE
docs: make parameter style consistent

### PR DESCRIPTION
**Pull request by robert-ancell**

### CODE REVIEW

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by zyga** [comment]
Looks good, +1

**Comment by chipaca** [comment]
I'm not sure I understand. The uuid is not optional.

**Comment by chipaca** [comment]
Now I understand. Hmmm.

**Comment by niemeyer** [comment]
Yeah, should we make it consistent on the other direction?

**Comment by robert-ancell** [comment]
Sorry, I didn't mention the issue properly but when you visit https://github.com/ubuntu-core/snappy/blob/master/docs/rest.md the <uuid> is not shown, probably because it looks like an XML tag.

**Comment by niemeyer** [comment]
Thanks!

**Pull request merged**
