### PR TITLE
client: enable retrieving asynchronous operation information with `Client.Operation`.

### PR DESCRIPTION
**Pull request by chipaca**

### CODE REVIEW

**Comment by niemeyer** [comment]
LGTM once tests are fixed (s/Get//).

**Comment by mvo5** [comment]
:+1:

**Comment by stevenwilkin** [comment]
:+1: 

So the output of the operation isn't exposed here which is fine. For operations that __WebDM__ is interested in then perhaps I can build on top of this and include the "progress" percentage, this way the endpoint could be polled until the operation had completed.

**Comment by mvo5** [comment]
Fwiw, I would prefer if we would remove the `snappy install ` command with progress reporting only once  `snap add` also progress reporting. Which seems like not that far off :)

**Pull request merged**
