### PR TITLE
interfaces: add x from ubuntu-core-security

### PR DESCRIPTION
**Pull request by jdstrand**
interfaces: add x from ubuntu-core-security

### CODE REVIEW

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by elopio** [comment]
wow, lots of work and lots of tests, thanks Jamie.
This will need high level tests to make sure that we can install and use snaps with these interfaces. Please get in contact with me and @fgimenez to help you writing them.

**Comment by jdstrand** [comment]
On Wed, 2016-03-23 at 23:32 -0700, Leo Arias wrote:
> wow, lots of work and lots of tests, thanks Jamie.
> This will need high level tests to make sure that we can install and use snaps
> with these interfaces. Please get in contact with me and @fgimenez to help you
> writing them.
> 
Note, this is just moving these:

(15.04):
services:
  - name: foo
    caps: [networking]

(or old-security 16.04):
apps:
  foo:
    plugs: mysecurity

plugs:
  mysecurity:
    interface: old-security
    caps: [network-client]

to this:
apps:
  foo:
    plugs: [network]

What I'm getting at is that if there are already tests for 15.04/caps or previously 16.04/old-security/caps, then they just need to be translated.


-- 
Jamie Strandboge             | http://www.canonical.com

**Comment by chipaca** [comment]
ok to test

**Comment by mvo5** [comment]
Fine, maybe x11 instead of just x? but I don't really mind either way.

**Comment by jdstrand** [comment]
'x' was used because that was what was agreed upon between Gustavo, Zygmunt and myself.

**Comment by niemeyer** [comment]
I'm merging all security interface branches, and adding a single card in Trello to track the points raised which were not addressed.

**Pull request merged**
