### PR TITLE
integration-tests: always use the built snapd when compiling binaries from branch

### PR DESCRIPTION
**Pull request by fgimenez**

### CODE REVIEW

**Comment by mvo5** [comment]
:+1:

**Comment by elopio** [comment]
I'm ok with this. As we discussed, we need to find a way to not run this commands when listing the tests. I'm looking now at integration-tests/scripts/test-wrapper. The sad part is that it's bash. Alternatively, we could run the init only if we are in a snappy system.
And a note here for the future: we are no longer stoping the daemon. That might be useful to add to the commit description, but here in the discussion is ok to.

**Comment by mvo5** [comment]
I agree that the fact that the daemon is no longer stopped is something that would be nice to have in the git log. Maybe a simple `git commit --amend` and `git push -f` :) ? Otherwise this looks fine.

**Comment by fgimenez** [comment]
> Alternatively, we could run the init only if we are in a snappy system.

Yes, we need that, we can discuss about the required changes.

> I agree that the fact that the daemon is no longer stopped is something that would be nice to have in the git log.

@mvo5 sure, i'll push the changes now. 

However it seems that the daemon was not stopped for real, the `s.cmd.Process.Kill()` call was killing the parent process (systemd-activate or perhaps something else given that sudo is involved) and not the forked one (the actual daemon). This will be handled in an upcoming branch, I'll state in the commit message that the kill call is being removed.

**Comment by fgimenez** [comment]
@mvo5 commit message updated, pls take a look.

Thanks! :)

**Comment by mvo5** [comment]
Thanks!

**Pull request merged**
