### PR TITLE
many: move store and related services access support code to its own store package

### PR DESCRIPTION
**Pull request by pedronis**
This moves store and related services access support code to its own store package. It tries to keep relatively clean separation of concerns, store should not know about local system decisions/layouts.

### CODE REVIEW

**Comment by mvo5** [comment]
Thanks for doing this work! Looks fine and I really really like that the store is no longer part of snappy/.

**Comment by mvo5** [comment]
It appears that the integration tests need a small update:
```
/home/jenkins-slave/workspace/github-snappy-integration-tests-cloud@2/src/github.com/ubuntu-core/snappy/integration-tests/tests/installApp_test.go:88:
... obtained string = "" +
...     "Installing unexisting.canonical\n" +
...     "unexisting.canonical failed to install: snap not found\n"
... expected string = "" +
...     "Installing unexisting.canonical\n" +
...     "unexisting.canonical failed to install: snappy package not found\n"
... Wrong error message
```

**Comment by pedronis** [comment]
retest this please

**Comment by pedronis** [comment]
@mvo5 @chipaca so the one integration failure we have is because the fake store used by the integration tests doesn't return revisions  but just versions still I think

**Pull request merged**
