### PR TITLE
Add an interface for snapd API clients

### PR DESCRIPTION
**Pull request by stevenwilkin**
I've been using an interface in order to mock responses from the `snapd` API under test in __WebDM__. I'm not 100% sure wether this best belongs in __WebDM__ or here.

Any opinions?

### CODE REVIEW

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by zyga** [comment]
No objection from me, this might make testing CLI tools much easier.

**Comment by stevenwilkin** [comment]
Cheers @zyga.

I originally tried using some single method interfaces so that I could construct mocks to pass into methods under test but with methods that needed to hit more than just one endpoint in the API it seemed better to work against a more complete interface.

For instance, I've the following struct which can be embedded or otherwise modified to suit a specific test case:

```go
type fakeSnapdClient struct{}

func (f *fakeSnapdClient) SysInfo() (*client.SysInfo, error)                      { return &client.SysInfo{}, nil }
func (f *fakeSnapdClient) Capabilities() (map[string]client.Capability, error)    { return nil, nil }
func (f *fakeSnapdClient) AddCapability(c *client.Capability) error               { return nil }
func (f *fakeSnapdClient) RemoveCapability(name string) error                     { return nil }
func (f *fakeSnapdClient) Packages() (map[string]client.Package, error)           { return nil, nil }
func (f *fakeSnapdClient) Services(pkg string) (map[string]client.Service, error) { return nil, nil }

func (f *fakeSnapdClient) Icon(pkgID string) (client.Icon, error) {
    icon := client.Icon{
        Filename: "icon.png",
        Content:  []byte("png"),
    }   
    return icon, nil 
}
```

**Comment by chipaca** [comment]
feels a bit wrong to define an interface and not use it, tbh =)

**Comment by stevenwilkin** [comment]
Do you think this interface would better belong in __WebDM__ then @chipaca?

The motivation for introducing it is to help with testing which I'm sure would be beneficial for contributors other than myself but if no one else is actually going to make of it then it's just noise.

FWIW, we can ensure that the `Client` struct conforms to the interface thus:
```go
var _ SnapdClient = (*Client)(nil)
```

**Comment by chipaca** [comment]
We can make `Client` be private and only expose the interface; I think that's the approach I'd favour right now (but this is the kind of thing I flip-flop over still; maybe @niemeyer can chime in)

**Comment by stevenwilkin** [comment]
Makes sense, we'd still have `client.New()` to return something fitting the interface.

**Comment by niemeyer** [comment]
@mvo5 is working on a fake implementation of the store for tests as well. Rather than faking the client, which implies having to mimic the server behavior for every single answer, I'd prefer to have that implementation of a fake server which is more than a stub. That fake server should actually behave as a server, and know how to respond to arbitrary queries even if the test says nothing. The interface between the fake server and the test should be one of configuration, rather than what is usually termed "mocking". In other words, we don't want to inject server responses themselves.. we want to tell that fake server what it contains in a high-level API.

How does that sound?

**Comment by stevenwilkin** [comment]
So the fake server would still be communicated with via HTTP @niemeyer?

I can see the usefulness of that for a certain category of test. I think other tests would benefit more from the use of a fake client though, it would come down to the test boundaries and the collaborators involved.

Perhaps there just isn't a place for this interface in this package currently apart from the possible use by @zyga in the future.

**Comment by niemeyer** [comment]
@stevenwilkin That sounded a bit too vague to agree/disagree with. What are the category of tests this wouldn't be useful for and why?

**Comment by stevenwilkin** [comment]
The code I'm working with atm @niemeyer is concerned with having some form of client that will provide it with a list of available packages.

I feel in this situation using an interface with a `Packages()` method is acceptable as it easily allows me to focus on the responsibility of my own code. A fully fledged fake server __could__ also be used in conjunction with a real client but I wouldn't say it was strictly necessary.

**Comment by niemeyer** [comment]
Sure, it's not strictly necessary. The point is that if you had such an implementation to begin with, it would solve your problem very well. It also solves a number of other related test cases for which a trivial fake client wouldn't be so appropriate, which is why @mvo5 is working on it ATM.

**Comment by niemeyer** [comment]
I'm closing this for the time being since there seems to be no +1s on the suggested interface. If you'd still like to pursue that let's please catch up online.

**Comment by stevenwilkin** [comment]
I was going to suggest similar @niemeyer!

**Pull request closed without merging**
