### PR TITLE
Feature/remove click hooks support

### PR DESCRIPTION
**Pull request by mvo5**
Build on top of the native-security branch, once thats in this branch diff is a lot smaller.

This removes support to run click hooks on install of snaps. The last hook we used was the aa-clickhook which is now done internally.

### CODE REVIEW

**Comment by niemeyer** [comment]
Same: please ping once the top one is in so we can move reviews forward.

**Comment by chipaca** [comment]
so much red has *got* to be good. :+1:

**Comment by niemeyer** [comment]
LGTM, of course!

**Comment by niemeyer** [comment]
Except.. it is in conflict.. aw.. almost.

**Pull request merged**
