### PR TITLE
Ensure that "{enable,destroy}-classic" are run as root

### PR DESCRIPTION
**Pull request by mvo5**
Trivial branch that just ensures that enable/destroy classic are run as root. Silly me for forgetting that check in the first place.
Fixes https://bugs.launchpad.net/bugs/1530826

### CODE REVIEW

**Comment by elopio** [comment]
This is a bug right? Can you please report it in launchpad with the steps to reproduce it?
Also, I think this needs tests. Maybe an integration test running enable and destroy as root, and a unit test that checks the error message when run not as root.

**Comment by chipaca** [comment]
any reason for not using the lock for these?

**Comment by mvo5** [comment]
@chipaca Yes, No, NO - thanks for the suggestion, I fixed it to use the lock now.

**Comment by mvo5** [comment]
@elopio thanks for the suggestion. The LP link is in the first comment, I added instructions how to reproduce the bug and the fix there.

**Comment by chipaca** [comment]
:+1:

**Pull request merged**
