### PR TITLE
interfaces: add log-observe from ubuntu-core-security

### PR DESCRIPTION
**Pull request by jdstrand**
interfaces: add log-observe from ubuntu-core-security

### CODE REVIEW

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by chipaca** [comment]
add to whitelist

**Comment by mvo5** [comment]
This looks fine. Fwiw I used https://github.com/ubuntu-core/snappy/compare/master...jdstrand:log-observe?expand=1 to compare, for some reason the github diff included changes that are already in master.

However I doubt the value of the tests, it seems they are mostly testing what is already tested from commonInterface, i.e. the NewLogObserverInterface in itself has only the apparmor snippet and the name that is unique and different from commonInterface.

**Comment by zyga** [comment]
LGTM

FYI: for tests I'd keep them as is. It will be easier to add interface-specific tests (e.g. regression checks or anything similar) this way. We could spend some time de-duplicating them after 16.04.

**Comment by niemeyer** [comment]
I'm merging all @jdstrand's security interface branches, and adding a single card in Trello to track the points raised which were not addressed.

**Pull request merged**
