### PR TITLE
integration-tests: changed default release to 16

### PR DESCRIPTION
**Pull request by fgimenez**

### CODE REVIEW

**Comment by pedronis** [comment]
mmh, have you tried this locally?  wondering a bit whether u-d-f will send 16-core (which is not a thing) or just 16 (which is the actual name)

**Comment by fgimenez** [comment]
@pedronis yes, with the current master and latest udf i'm getting 
```
$ go run ./integration-tests/main.go 
Building tests...
go test -c ./integration-tests/tests
Creating image...
sudo ubuntu-device-flash --verbose core rolling --output /tmp/snappy-test/image/snappy-rolling-edge-latest.img --channel edge --gadget canonical-pc --os ubuntu-core --kernel canonical-pc-linux --developer-mode
[sudo] password for fgimenez: 
Determining gadget configuration
expected a gadget snaps: snap not found
2016/04/25 12:12:48 Error while running [sudo ubuntu-device-flash --verbose core rolling --output /tmp/snappy-test/image/snappy-rolling-edge-latest.img --channel edge --gadget canonical-pc --os ubuntu-core --kernel canonical-pc-linux --developer-mode]: exit status 1
panic: Error while running [sudo ubuntu-device-flash --verbose core rolling --output /tmp/snappy-test/image/snappy-rolling-edge-latest.img --channel edge --gadget canonical-pc --os ubuntu-core --kernel canonical-pc-linux --developer-mode]: exit status 1


goroutine 1 [running]:
log.Panicf(0x63a600, 0x1b, 0xc8200b99b8, 0x2, 0x2)
	/usr/local/go/src/log/log.go:327 +0xd8
github.com/ubuntu-core/snappy/integration-tests/testutils/testutils.ExecCommand(0xc8200a8000, 0x10, 0x10, 0x0, 0x0)
	/home/fgimenez/workspace/gocode/src/github.com/ubuntu-core/snappy/integration-tests/testutils/testutils/testutils.go:59 +0x3ca
github.com/ubuntu-core/snappy/integration-tests/testutils/image.Image.UdfCreate(0x60f900, 0x7, 0x60e778, 0x4, 0x0, 0x0, 0x631500, 0x10, 0x633f80, 0x12, ...)
	/home/fgimenez/workspace/gocode/src/github.com/ubuntu-core/snappy/integration-tests/testutils/image/image.go:68 +0x5e3
main.main()
	/home/fgimenez/workspace/snappy/integration-tests/main.go:134 +0xb4d
exit status 2
```

With this change, using `16` as the default release, the image build step works:
```
$ go run ./integration-tests/main.go 
Building tests...
go test -c ./integration-tests/tests
Creating image...
sudo ubuntu-device-flash --verbose core 16 --output /tmp/snappy-test/image/snappy-16-edge-latest.img --channel edge --gadget canonical-pc --os ubuntu-core --kernel canonical-pc-linux --developer-mode
Determining gadget configuration
84.00 KB / 84.00 KB [============================================================================================================================] 100.00 % 688.04 KB/s 0
Parallel unsquashfs: Using 8 processors
5 inodes (4 blocks) to write

/tmp/gadget708489482/gadget/fake-gadget/1.0-fake
/tmp/gadget708489482/gadget/fake-gadget/1.0-fake/canonical-pc_3.0_all.snap
/tmp/gadget708489482/gadget/fake-gadget/1.0-fake/canonical-pc_3.1_all.snap
/tmp/gadget708489482/gadget/fake-gadget/1.0-fake/grub.cfg
/tmp/gadget708489482/gadget/fake-gadget/1.0-fake/meta
/tmp/gadget708489482/gadget/fake-gadget/1.0-fake/meta/icon.png
/tmp/gadget708489482/gadget/fake-gadget/1.0-fake/meta/snap.yaml

created 5 files
created 2 directories
created 0 symlinks
created 0 devices
created 0 fifos

Partitioning...
Formatting...
Mounting...
Provisioning...
64.64 MB / 64.64 MB [============================================================================================================================] 100.00 % 1.17 MB/s 55s
Installing canonical-pc
84.00 KB / 84.00 KB [============================================================================================================================] 100.00 % 476.73 KB/s 0
Installing canonical-pc-linux
109.53 MB / 109.53 MB [======================================================================================================================] 100.00 % 836.64 KB/s 2m14s
Installing ubuntu-core
64.64 MB / 64.64 MB [===========================================================================================================================] 100.00 % 1.05 MB/s 1m1s
Removing unneeded: /tmp/diskimage161872588/boot/EFI/ubuntu/grub/canonical-pc-linux_24.snap
Enabling developer mode...
Unmounting...
New image complete
Summary:
 Output: /tmp/snappy-test/image/snappy-16-edge-latest.img
 Architecture: amd64
 Channel: edge
 Version: 0
Calling adt-run...
adt-run -B --override-control integration-tests/data/output/control --built-tree /home/fgimenez/workspace/snappy --output-dir /tmp/snappy-test/output --setup-commands touch /run/autopkgtest_no_reboot.stamp --env no_proxy=127.0.0.1,127.0.1.1,localhost,login.ubuntu.com --env http_proxy= --env https_proxy= --- ssh -s /usr/share/autopkgtest/ssh-setup/snappy -- -b -i /tmp/snappy-test/image/snappy-16-edge-latest.img
adt-run [12:30:27]: version 3.20.4
adt-run [12:30:27]: host arkham; command line: /usr/bin/adt-run -B --override-control integration-tests/data/output/control --built-tree /home/fgimenez/workspace/snappy --output-dir /tmp/snappy-test/output --setup-commands 'touch /run/autopkgtest_no_reboot.stamp' --env no_proxy=127.0.0.1,127.0.1.1,localhost,login.ubuntu.com --env http_proxy= --env https_proxy= --- ssh -s /usr/share/autopkgtest/ssh-setup/snappy -- -b -i /tmp/snappy-test/image/snappy-16-edge-latest.img
.........
```

Anyway this default value can always be overridden using the `-release` flag.

**Comment by zyga** [comment]
Looks good

**Comment by pedronis** [comment]
yes, I looked at u-d-f, it indeed uses the release correctly though in a big hammer sort of way, after all because it is using snappy store code in the end

**Pull request merged**
