### PR TITLE
Refactor/all snaps integration tests

### PR DESCRIPTION
**Pull request by mvo5**
This branch ports the integration tests to the all-snap architecture. Some tests are skipped right now due to the following bug:

https://bugs.launchpad.net/snappy/+bug/1534029

I think its still useful to have the other tests. The server will need the ubuntu-device-flash from http://people.canonical.com/~mvo/all-snaps/ (or build from lp:~snappy-dev/goget-ubuntu-touch/all-snaps). 

This also includes the mini store server.

### CODE REVIEW

**Comment by mvo5** [comment]
Closing again, for some reason I see new failures that I did not see before.

**Comment by fgimenez** [comment]
:+1: amazing, congrats!

**Comment by chipaca** [comment]
woo to the hoo! :+2:

**Comment by elopio** [comment]
I've just gotten back my results:
----------------------------------------------------------------------
Ran 54 tests in 0.007s

OK (skipped=5)

Great job everybody!!!

**Pull request merged**
