### PR TITLE
interfaces: add unity7 interface from ubuntu-core-security

### PR DESCRIPTION
**Pull request by jdstrand**
interfaces: add unity7 interface from ubuntu-core-security

### CODE REVIEW

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by chipaca** [comment]
ok to test

**Comment by mvo5** [comment]
Fine

**Comment by niemeyer** [comment]
Should this be "unity" instead of "unity7"?

I'm merging all security interface branches, and adding a single card in Trello to track the points raised which were not addressed.

**Pull request merged**
