### PR TITLE
Set `Content-Disposition` header to filename when serving a `FileResponse`

### PR DESCRIPTION
**Pull request by stevenwilkin**
As promised @chipaca :gift:

### CODE REVIEW

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by chipaca** [comment]
ok to test

**Comment by chipaca** [comment]
:+1: on this.

If the icon filename is UTF-8 the current thing might not work with some browsers. As we're moving to having the icon be inferred by convention rather than prescribed, I'm fine with that.

**Comment by mvo5** [comment]
Nice!

**Pull request merged**
