### PR TITLE
Revert "Merge pull request #209 from mvo5/refactor/sys-unix"

### PR DESCRIPTION
**Pull request by mvo5**
This reverts commit 3b4f58461b13e41578772aab2cf6ab05ae123d30, reversing
changes made to 724e87ee8c28a1b608cc9789d60bfa411f6bed75.

Trivial branch that reverts using x/sys/unix for the sys.Utimes() call. This syscall
is not implemented on arm64 so the test fails. Using sys.Utime() fails on armhf
so the easiest option is to just use "touch". If this was outside a test it would be
worthwhile to implement Utime via cgo but I think for this use-case its overkill.

### CODE REVIEW

**Comment by mvo5** [comment]
retest this please

**Comment by chipaca** [comment]
:+1:

**Comment by fgimenez** [comment]
As a side note it seems that the integration test is failing because the fix from #284 is not included in this tree, in order to do so this branch can be rebased to the tip of master or cherrypick that specific commit.

**Comment by niemeyer** [comment]
Love the explanation!

**Pull request merged**
