### PR TITLE
Removing the concept of vendor

### PR DESCRIPTION
**Pull request by sergiusens**
Fixes LP: #1510522

Signed-off-by: Sergio Schvezov <sergio.schvezov@canonical.com>

### CODE REVIEW

**Comment by elopio** [comment]
You touched 32 files. I better EOD now. This review will have to wait for early tomorrow :)

**Comment by chipaca** [comment]
This is a backwards-incompatible change to the daemon api, so you need to add an api version, and add code that produces the new api, and change the old api to add back the key you're removing here.

As there's talk of more metadata changes, I'd wait for things to settle before embarking on implementing this change. In any case, :-1: as it stands.

**Comment by sergiusens** [comment]
@chipaca how are things now?

**Comment by niemeyer** [comment]
I'm keeping this for @chipaca. Please ping when/if he's happy.

**Comment by niemeyer** [comment]
@chipaca As a side note, given @sergiusens went over the trouble of bootstrapping this, it would be nice to agree on how we want to do this at least, now or in the future, so we have some guidelines for making progress on those agreements we made and can unblock @sergiusens for making further progress.

**Comment by chipaca** [comment]
@niemeyer @sergiusens's question about “how are things now” came after we'd agreed on how we wanted this, and he'd implemented it.

:+1:

**Comment by niemeyer** [comment]
Okay, merging it then. Thanks to both.

**Pull request merged**
