### PR TITLE
Make services also starting in SNAP_DATA as cwd

### PR DESCRIPTION
**Pull request by didrocks**
Previous branch was patching the wrapper, which is only used for commands. Achieving thus the same for services and adapt tests for it.

Note: I'm using a similar way than in the wrapper to change WorkingDirectory. I'm opened as well to add a .UserData to the struct and assign it as we do for .SnapPath if necessary.
static and unit tests works.

### CODE REVIEW

**Comment by chipaca** [comment]
:+1:

**Comment by zyga** [comment]
This breaks one of the integration tests. Please fix it first.

**Comment by didrocks** [comment]
@zyga https://github.com/ubuntu-core/snappy-testdata/pull/5 will fix the broken integration test. It needs to be uploaded just a little bit before to the store before merging this branch.

**Comment by zyga** [comment]
retest this please

**Comment by didrocks** [comment]
retest this please

**Comment by didrocks** [comment]
xkcd-webserver 16.04-2 was still used in the latest test run when 16.04-4 was already marked as published (maybe there is a little bit of a delay?). Checked again that -4 is marked as published, retrying then.
restest this please.

**Comment by didrocks** [comment]
I'm still puzzled why from the logs
xkcd-webserver     2016-03-03 16.04-2    canonical
is still installed.

Even more puzzled that on my 16.04 Ubuntu Core VM:
$ snap find xkcd
Name                     Version Summary
xkcd-webserver.canonical 3.0     xkcd-webserver

@zyga: you may have an idea here?

**Comment by didrocks** [comment]
should be good now (some parts were not fully published).
retest this please.

**Comment by didrocks** [comment]
Image creation issue:
```2016/03/15 08:02:48 Error while running [openstack server create --security-group ssh --flavor m1.medium --image ubuntu-core/custom/ubuntu-rolling-snappy-core-amd64-edge-20160313202220.976646-disk1.img test-19558]: exit status 1
2016/03/15 08:02:48 Error creating image for release rolling and channel edge, exit status 1
panic: Error creating image for release rolling and channel edge, exit status 1
```
let's get another run:
retest this please.

**Comment by didrocks** [comment]
Another infra failure:
```
adt-run [08:06:29]: host e293534da142; command line: /usr/bin/adt-run -B --override-control integration-tests/data/output/control --built-tree /home/jenkins-slave/workspace/github-snappy-integration-tests-cloud/src/github.com/ubuntu-core/snappy --output-dir /home/jenkins-slave/workspace/github-snappy-integration-tests-cloud/jenkins-github-snappy-integration-tests-cloud-517/output --setup-commands 'touch /run/autopkgtest_no_reboot.stamp' --env http_proxy=http://squid.internal:3128 --env https_proxy=http://squid.internal:3128 --env no_proxy=127.0.0.1,127.0.1.1,localhost,login.ubuntu.com --- ssh -H -snappy-from-branch -p 22 -l ubuntu -i /home/jenkins-slave/.ssh/id_rsa --reboot --timeout-ssh 600
usage: adt-virt-ssh [-h] [-d] [-H HOSTNAME] [-i IDENTITY] [-l LOGIN]
                    [-P PASSWORD] [-p PORT] [-o OPTIONS] [-r]
                    [-s SETUP_SCRIPT] [--timeout-ssh SECS]
                    ...
adt-virt-ssh: error: argument -H/--hostname: expected one argument
adt-run [08:06:30]: ERROR: testbed failure: cannot send to testbed: ['BrokenPipeError: [Errno 32] Broken pipe\n']
2016/03/15 08:06:30 Error while running [adt-run -B --override-control integration-tests/data/output/control --built-tree /home/jenkins-slave/workspace/github-snappy-integration-tests-cloud/src/github.com/ubuntu-core/snappy --output-dir /home/jenkins-slave/workspace/github-snappy-integration-tests-cloud/jenkins-github-snappy-integration-tests-cloud-517/output --setup-commands touch /run/autopkgtest_no_reboot.stamp --env http_proxy=http://squid.internal:3128 --env https_proxy=http://squid.internal:3128 --env no_proxy=127.0.0.1,127.0.1.1,localhost,login.ubuntu.com --- ssh -H -snappy-from-branch -p 22 -l ubuntu -i /home/jenkins-slave/.ssh/id_rsa --reboot --timeout-ssh 600]: exit status 16
panic: Error while running [adt-run -B --override-control integration-tests/data/output/control --built-tree /home/jenkins-slave/workspace/github-snappy-integration-tests-cloud/src/github.com/ubuntu-core/snappy --output-dir /home/jenkins-slave/workspace/github-snappy-integration-tests-cloud/jenkins-github-snappy-integration-tests-cloud-517/output --setup-commands touch /run/autopkgtest_no_reboot.stamp --env http_proxy=http://squid.internal:3128 --env https_proxy=http://squid.internal:3128 --env no_proxy=127.0.0.1,127.0.1.1,localhost,login.ubuntu.com --- ssh -H -snappy-from-branch -p 22 -l ubuntu -i /home/jenkins-slave/.ssh/id_rsa --reboot --timeout-ssh 600]: exit status 16
```

**Comment by mvo5** [comment]
retest this please

**Comment by didrocks** [comment]
retest this please

**Comment by didrocks** [comment]
retest this please

**Comment by mvo5** [comment]
retest this please

**Comment by didrocks** [comment]
@mvo5: Finally, a run without any flackyness failures! :)

**Pull request merged**
