### PR TITLE
store: use purchase decorator in Snap and FindSnaps

### PR DESCRIPTION
**Pull request by pete-woods**

### CODE REVIEW

**Comment by chipaca** [comment]
Note you can test that you logged what you meant to log in the error cases using something like [this](https://github.com/ubuntu-core/snappy/pull/1143/commits/8b60ee47216775dee3afba8dbd7510d126542be8#diff-dd8b645d24617da2d614f17d3f68d3ddL42) (also note that particular diff is reverted in a later commit on that particular pull request).

**Comment by mvo5** [comment]
:+1:

**Comment by pete-woods** [comment]
@chipaca Thanks! Have just added a similar test to the suite.

**Comment by chipaca** [comment]
This LGTM. There's a branch by yours truly to make the decorator not loop that much, but it shouldn't block this.

**Comment by chipaca** [comment]
retest this please

**Comment by chipaca** [comment]
retest this please?

**Comment by fgimenez** [comment]
retest this please

**Comment by chipaca** [comment]
retest this please

**Pull request merged**
