### PR TITLE
add security whitepaper

### PR DESCRIPTION
**Pull request by dholbach**
As the original of the text has footnotes, this requires the footnotes extension (https://pythonhosted.org/Markdown/extensions/footnotes.html), if we want the ToC to be on the page, we need the toc extension (https://pythonhosted.org/Markdown/extensions/toc.html), both are enabled on developer.ubuntu.com where we'd like to import the doc into.

### CODE REVIEW

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by dholbach** [comment]
Generated version available at: https://daniel.holba.ch/temp/whitepaper/security-whitepaper.html for review.

**Comment by niemeyer** [comment]
I would prefer to not merge such whitepaper-styled documentation into the repository. The content is certainly interesting, but it's very long, monolithic, and hard to update. This should probably be a PDF somewhere instead, with a link mentioning context, author, and date for the document.

**Comment by niemeyer** [comment]
Temporarily closing this. Let's chat online.

**Pull request closed without merging**
