### PR TITLE
Feature/all snap reboot required

### PR DESCRIPTION
**Pull request by mvo5**
[build on top of mvo5:feature/kernel-os-type so once that is merged the diff will be a lot smaller]

Small branch that implements the "reboot-required" detection (visible e.g. in snappy list).

### CODE REVIEW

**Comment by niemeyer** [comment]
LGTM given the current state of affairs, but I find it unfortunate to have such an interface hooked up to the SnapPart. This is very clearly not a property of any one snap in the system, but rather of the system itself. Why would we ask every snap whether _they_ need a reboot just so we can read the _global_ system understanding of whether a reboot is necessary?

**Comment by mvo5** [comment]
@niemeyer Thanks a bunch for the review. I think I understand your concern about the current interface. Do you have something like mvo5:feature/all-snap-reboot-required-refactor in mind when it comes to improving it? This branch provides a "requireRebootParts() (result []Part, err error)" that returns a list of parts that require a reboot. This would replace the "NeedsReboot()" function that is currently part of the SnapPart code. Is that what you have in mind? If so, I can continue with that branch later.

**Comment by zyga** [comment]
(a bit of chat from Telegram)
```
Michael Vogt, [20.11.15 09:55]
I have two tiny reviews waiting if someone wants to give them a go :)

Zygmunt Krynicki, [20.11.15 09:59]
(re, I'll check them out @mvogt )

Zygmunt Krynicki, [20.11.15 10:01]
@mvogt if you rename NeedsReboot to DesiresSystemReboot() it would be more indicative of what the relationshp between classes is

Zygmunt Krynicki, [20.11.15 10:02]
I see what Gustavo meant but I also see why a part would want to indicate it desires the system to reboot

Zygmunt Krynicki, [20.11.15 10:02]
still, if you are going to continue on the path from the 2nd branch then I don't want to hold this
```

**Comment by mvo5** [comment]
I put a strawman branch here: https://github.com/mvo5/snappy/tree/feature/all-snap-reboot-required-refactor - pleae let me know if that is what you had in mind.

**Comment by zyga** [comment]
Let's not hold this. We can easily revisit that next week. Landing this today will make all-snaps complete (with another branch landing alongside it) and that's an important milestone to reach.

**Pull request merged**
