### PR TITLE
integration-tests/snapd: fix the start of the test snapd socket

### PR DESCRIPTION
**Pull request by elopio**

### CODE REVIEW

**Comment by elopio** [comment]
For some reason I don't understand, the systemd-activate can no longer parse the -E argument:
https://paste.ubuntu.com/15122662/
So, to fix this we pass the long argument name.

**Comment by chipaca** [comment]
Good sleuthing! thank you for this :+1:

**Comment by mvo5** [comment]
Yay!

**Comment by elopio** [comment]
For the record, upstream bug reporte: systemd/systemd/issues/2658

**Pull request merged**
