### PR TITLE
interfaces: update for recent ubuntu-core-security updates

### PR DESCRIPTION
**Pull request by jdstrand**
interfaces/seccomp.go: update for recent ubuntu-core-security updates

### CODE REVIEW

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by zyga** [comment]
+1

**Comment by zyga** [comment]
whitelist this please

**Pull request merged**
