### PR TITLE
integration-tests: send fake revision that is higher than the installed one

### PR DESCRIPTION
**Pull request by mvo5**
Please only merge if the integration tests really are green. This sets the revision that the store sends to a higher number than the local revision (which is 0).

### CODE REVIEW

**Comment by mvo5** [comment]
retest this please

**Comment by chipaca** [comment]
retest this plase
dance for us,
little bot.

**Comment by chipaca** [comment]
:+1: 
also, I count @elopio 's comments on telegram as another :+1:.

**Comment by pedronis** [comment]
retest this please

**Comment by elopio** [comment]
thank you!

**Pull request merged**
