### PR TITLE
integration-tests: add fromBranch config field

### PR DESCRIPTION
**Pull request by fgimenez**
Also define the default config file path as a constant in the config package

### CODE REVIEW

**Comment by mvo5** [comment]
Thanks, this looks fine in itself. While reading the code I noticed the NewConfig(configFileName, "testrelease", "testchannel", false, true, true, true) - the booleans in there I find a bit hard to read, i.e. which one applies to which parameter. Therefor I created a pull request https://github.com/fgimenez/snappy/pull/1 that may make this a bit easier to read by just using the struct directly without the constructor. I hope you like that as well.

**Comment by fgimenez** [comment]
@mvo5 sure, thanks! :) much better, I'll add those changes to this PR

**Comment by mvo5** [comment]
@fgimenez Great! Thanks. Just merging the pull-request is probably the simplest way, then it should appear here and I give it another :+1:

**Comment by fgimenez** [comment]
@mvo5 ok done :)

**Comment by mvo5** [comment]
:+1:

**Comment by elopio** [comment]
+1, thanks Federico.

**Pull request merged**
