### PR TITLE
snappy,systemd: remove "ports" from snap.yaml

### PR DESCRIPTION
**Pull request by mvo5**
We decided to remove "ports" from the snap.yaml a while ago. This branch implements it. The slightly scary part is that this also has implications for the startup ordering of the snaps. I.e. a snap can no longer rely on network being available. If @chipaca could chime in here, that would be great, iirc we added this for webdm in the past. OTOH on a regular system there is no grantee that network is available when e.g. apache is started so it seems like its really a issue that webdm should deal with instead of the system itself(?).

### CODE REVIEW

**Comment by mvo5** [comment]
@chipaca was so kind to explain that right now the ordering is criticial for the webdm avahi support. it uses internally "listenIPv4MulticastUDP" which does not have the right setsockopt options to bind to a not-ready interface.

**Comment by niemeyer** [comment]
The fact we use the ports information to fix a completely unrelated problem but to nothing at all relevant to ports themselves feels like a great indication that we should get rid of this feature until we have a better understanding of the problems we want them  to solve, and how we want to solve these.

For webdm, isn't it still a bug there, though?  Knowing that the request can fail because the network isn't ready (something very common), why isn't it retrying rather exploding?

We can special-case webdm for the time being, but it feels like something is amiss there.

**Comment by niemeyer** [comment]
LGTM

**Comment by chipaca** [comment]
I'd expect this to nuke the wait4network.service file. Other than that, :+1:

**Comment by mvo5** [comment]
@chipaca thanks, excellent point, I removed that unit now.

**Pull request merged**
