### PR TITLE
snappy: when using staging, authenticate there instead

### PR DESCRIPTION
**Pull request by alecu**

### CODE REVIEW

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by chipaca** [comment]
add to whitelist

**Comment by chipaca** [comment]
:+1:

**Comment by alecu** [comment]
@chipaca: any idea why the integration tests may be failing? the "_StringException" there is not very useful.

**Comment by zyga** [comment]
+1

**Comment by chipaca** [comment]
Not related to this. I'll request a re-run once we've fixed them (it's ongoing).

**Comment by chipaca** [comment]
retest this please

**Comment by chipaca** [comment]
retest this please
again
please

**Comment by elopio** [comment]
The integration tests error has nothing to do with this change, and makes no sense: https://paste.ubuntu.com/15125595/
snappy install is not finding the file that snappy build generated in the previous step. The same setup worked in the other hwAssign test. So, a retry should work.
@fgimenez ^ I ran the test in a loop without errors. Let's keep an eye in case it happens again.

**Comment by chipaca** [comment]
retest this please
dance for us, testing monkey.

**Comment by chipaca** [comment]
@fgimenez @elopio and it's there again. http://pastebin.ubuntu.com/15126149/

Please advise.

**Comment by elopio** [comment]
I merged this with master and ran the full suite locally. So whatever is failing seems to be specific to scalingstack, and not at all related with this change. :+1: from the manual m-o.

**Comment by fgimenez** [comment]
> @fgimenez @elopio and it's there again. http://pastebin.ubuntu.com/15126149/
> 
> Please advise.

@chipaca I can't reproduce it locally, but now we there's a new one, also only in the cloud instances, http://paste.ubuntu.com/15169442/

Can it be related to this? In that case the snap.yaml file is found after unpacking but the contents seem to be wrong.

**Comment by chipaca** [comment]
Yeap, that's "all-zeroes" content to me says there's a bug in *stack

**Pull request merged**
