### PR TITLE
debian: add needs-root to autopkgtest config

### PR DESCRIPTION
**Pull request by mvo5**

### CODE REVIEW

**Comment by mvo5** [comment]
Very nice, thank you!

**Comment by elopio** [comment]
:+1: 
With a note that this will run all the tests as root, and that's not what we want because we will like to verify some commands running as a normal user. As we discussed during the meeting, most of the current tests will use sudo anyway so we will look for a better solution later.

**Comment by chipaca** [comment]
Retest this please?

**Comment by mvo5** [comment]
https://github.com/ubuntu-core/snappy/compare/master...mvo5:bugfix/more-adt?expand=1 is an alternative version of this

**Pull request closed without merging**
